# User config
author: "OPENWOLF"
tagline: "OPENWOLF Investments"
description: "We invest in online stores and businesses with the goal of growing them in terms of sales or ad revenue, before handing them over to entrepreneurs looking to invest in an already established business."
keywords: "Openwolf, Openwolf Investments"
email: "support@openwolf.com"
facebook: "https://facebook.com/openwolfofficial"
medium: "https://medium.com/openwolf"
github: "https://github.com/openwolfco"
motto: "We are a growing global initiative that intends to form a community that invests in humanity."
goal: "50% of our profit share is alloted to empowering grassroots organizations that lift people out of poverty through education and entrepreneurship."

# Site config
baseurl: "/"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
