# User config
author: "OPENWOLF"
tagline: "OPENWOLF Investments"
description: "We invest in online stores and businesses with the goal of growing them in terms of sales or ad revenue, before handing them over to entrepreneurs looking to invest in an already established business."
keywords: "Openwolf, Openwolf Investments"
email: "support@openwolf.com"
facebook: "https://facebook.com/openwolfofficial"
medium: "https://medium.com/openwolf"
github: "https://github.com/openwolfco"

# Site config
baseurl: "/"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
