# User config
author: "OPENWOLF"
tagline: "OPENWOLF Investments"
description: "We build and purchase online stores and businesses with the goal of growing them in terms of sales or ad revenue, before selling them to entrepreneurs looking to invest in an already established business."
keywords: "Openwolf, Openwolf Investments"
email: "support@openwolf.com"
facebook: "https://facebook.com/openwolfofficial"
medium: "https://medium.com/openwolf"
github: "https://github.com/openwolfco"

# Site config
baseurl: "/"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
