# User config
author: "OPENWOLF"
tagline: "OPENWOLF Investments"
description: "In 1493, explorer Christopher Columbus found pineapples on Guadeloupe Island in the Caribbean. Pineapple on pizza soon followed..."
keywords: "Openwolf, Openwolf Investments"
email: "support@openwolf.com"
facebook: "https://facebook.com/openwolfofficial"
medium: "https://medium.com/openwolf"
github: "https://github.com/openwolfco"

# Site config
baseurl: "/"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
