# User config
author: "OPENWOLF"
tagline: "OPENWOLF Investments"
description: "In 1493, explorer Christopher Columbus found pineapples on Guadeloupe Island in the Caribbean. Pineapple on pizza soon followed..."
keywords: "Openwolf, Openwolf Investments"
email: "support@openwolf.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: "/"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
