# User config
author: "OPENWOLF"
tagline: "OPENWOLF Investments"
description: "We invest in online businesses with the goal of growing them in terms of sales or ad revenue. Our investors keep 30% of all profit generated through sales, and are entitled to their shares when an online store or business is sold on marketplaces or purchased by individual entrepreneurs."
keywords: "Openwolf, Openwolf Investments"
email: "support@openwolf.com"
facebook: "https://facebook.com/openwolfofficial"
medium: "https://medium.com/openwolf"
github: "https://github.com/openwolfco"
motto: "We are a growing global initiative that intends to form a community that invests in humanity."
goal: "50% of our profit share is allotted to empowering grassroots organizations that lift people out of poverty through education and entrepreneurship."

# Site config
baseurl: "/"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
